[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5.11"
eframe = "0.26.1"
egui = "0.26.2"
egui_plot = "0.26.2"
rand = "0.8.5"
